---
- name: Install Virtualbox Guest Additions
  become: true
  apt:
    pkg:
      - virtualbox-guest-utils
      - virtualbox-guest-x11
    state: present
  when: ansible_virtualization_type == "virtualbox"
