---
- name: Install Virtualbox
  become: true
  apt:
    pkg:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
      - virtualbox-qt
    state: present
